-- AlterTable
ALTER TABLE "Albums" ALTER COLUMN "title" SET DATA TYPE VARCHAR(45),
ALTER COLUMN "genre" SET DATA TYPE VARCHAR(45);

-- AlterTable
ALTER TABLE "Collaborators" ALTER COLUMN "slice_name" SET DATA TYPE VARCHAR(45);

-- AlterTable
ALTER TABLE "Playlists" ALTER COLUMN "title" SET DATA TYPE VARCHAR(45);

-- AlterTable
ALTER TABLE "Projects" ALTER COLUMN "project_name" SET DATA TYPE VARCHAR(45),
ALTER COLUMN "type" SET DATA TYPE VARCHAR(45),
ALTER COLUMN "privacy" SET DATA TYPE VARCHAR(45),
ALTER COLUMN "track_name" SET DATA TYPE VARCHAR(45),
ALTER COLUMN "genre" SET DATA TYPE VARCHAR(45);

-- AlterTable
ALTER TABLE "Tracks" ALTER COLUMN "explicit" SET DATA TYPE VARCHAR(45),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(45);

-- AlterTable
ALTER TABLE "Users" ALTER COLUMN "password" SET DATA TYPE VARCHAR(45),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(45);
